spring:
  application:
    name: cloud-configuration
  config:
    import: configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"