spring:
  application:
    name: driver-service-2
  datasource:  
    url: jdbc:oracle:thin:@10.90.1.105:1521/DEV
    username: HR
    password: HR
  jpa:
   properties: 
     hibernate:
       formal_sql: true
   show-sql: true
   hibernate:
     ddl-auto: update
 

server:
  port: 7070


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
management:   
  endpoints:  
    web:
      exposure:
        include:
        -  "*"